# Generated by Django 6.0.2 on 2026-04-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_campo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campo',
            options={},
        ),
        migrations.RemoveField(
            model_name='campo',
            name='slug',
        ),
        migrations.AddField(
            model_name='campo',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
