# Generated by Django 6.0.2 on 2026-05-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_campo', '0003_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='tipo_atividade',
            field=models.CharField(choices=[('plantio', 'Plantio'), ('colheita', 'Colheita'), ('poda', 'Poda'), ('irrigacao', 'Irrigação'), ('adubacao', 'Adubação'), ('controle_pragas', 'Controle de Pragas'), ('controle_doencas', 'Controle de Doenças'), ('limpeza', 'Limpeza'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
    ]
