# Generated by Django 6.0.2 on 2026-05-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_campo', '0005_registro_preco_registro_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='preco',
        ),
        migrations.AddField(
            model_name='registro',
            name='valor_gasto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Custo total da atividade', max_digits=10),
        ),
        migrations.AlterField(
            model_name='registro',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Número de eventos ou escala', max_digits=10),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tipo_atividade',
            field=models.CharField(choices=[('preparo_solo', 'Preparo do Solo'), ('plantio', 'Plantio'), ('adubacao', 'Adubação'), ('irrigacao', 'Irrigação'), ('capina', 'Capina / Controle de Mato'), ('controle_pragas_doencas', 'Controle de Pragas e Doenças'), ('colheita', 'Colheita')], max_length=30),
        ),
    ]
