# Generated by Django 6.0.2 on 2026-05-09 14:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_campo', '0006_remove_registro_preco_registro_valor_gasto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='tipo_atividade',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='valor_gasto',
        ),
        migrations.AddField(
            model_name='registro',
            name='ciclos_por_ano',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='registro',
            name='custo_adubo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='registro',
            name='custo_agua',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='registro',
            name='custo_aluguel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='registro',
            name='custo_colheita',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='registro',
            name='custo_defensivos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='registro',
            name='custo_energia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='registro',
            name='custo_manutencao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='registro',
            name='custo_mao_obra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='registro',
            name='custo_sementes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='registro',
            name='custo_transporte',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='registro',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='registro',
            name='quantidade_produzida',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
