# Generated by Django 6.0.2 on 2026-05-09 14:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_campo', '0007_remove_registro_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Número de eventos ou escala', max_digits=10),
        ),
        migrations.AddField(
            model_name='registro',
            name='tipo_atividade',
            field=models.CharField(blank=True, choices=[('preparo_solo', 'Preparo do Solo'), ('plantio', 'Plantio'), ('adubacao', 'Adubação'), ('irrigacao', 'Irrigação'), ('capina', 'Capina / Controle de Mato'), ('controle_pragas_doencas', 'Controle de Pragas e Doenças'), ('energia_combustivel', 'Energia / Combustível'), ('transporte_embalagem', 'Transporte / Embalagem'), ('colheita', 'Colheita')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='registro',
            name='valor_gasto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo total da atividade', max_digits=10),
        ),
    ]
