# Generated by Django 6.0.2 on 2026-05-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_campo', '0008_registro_quantidade_registro_tipo_atividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='quantidade_unidade',
            field=models.CharField(blank=True, default='', help_text='Unidade da quantidade', max_length=50),
        ),
    ]
