# Generated by Django 6.0.2 on 2026-05-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_campo', '0009_registro_quantidade_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='medida_tipo',
            field=models.CharField(blank=True, default='', help_text='Período ou medida de consumo, se aplicável', max_length=50),
        ),
        migrations.AddField(
            model_name='registro',
            name='recurso_tipo',
            field=models.CharField(blank=True, default='', help_text='Recurso utilizado, se aplicável', max_length=50),
        ),
    ]
