# Generated by Django 6.0.2 on 2026-05-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_campo', '0010_registro_medida_tipo_registro_recurso_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='custo_aluguel_padrao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='campo',
            name='custo_manutencao_padrao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='campo',
            name='saca_em_kg',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Quantos kg tem uma saca (padrão)', max_digits=7),
        ),
    ]
