# Generated by Django 6.0.2 on 2026-05-18 03:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_campo', '0011_campo_custo_aluguel_padrao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='tipo_atividade',
            field=models.CharField(blank=True, choices=[('preparo_solo', 'Preparo do Solo'), ('plantio', 'Plantio'), ('adubacao', 'Adubação'), ('irrigacao', 'Irrigação'), ('capina', 'Capina / Controle de Mato'), ('controle_pragas_doencas', 'Controle de Pragas e Doenças'), ('energia_combustivel', 'Energia / Combustível'), ('transporte_embalagem', 'Transporte / Embalagem'), ('manutencao', 'Manutenção'), ('aluguel', 'Aluguel'), ('colheita', 'Colheita')], default='', max_length=30),
        ),
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('aluguel', 'Aluguel/Uso da terra'), ('manutencao', 'Manutenção'), ('sementes', 'Sementes/Mudas'), ('adubo', 'Adubo/Fertilizantes'), ('defensivos', 'Defensivos/Agrotóxicos'), ('agua', 'Irrigação/Água'), ('mao_obra', 'Mão de Obra'), ('energia', 'Energia/Combustível'), ('transporte', 'Transporte/Embalagem'), ('outros', 'Outros')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos', to='diario_campo.registro')),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unidade', models.CharField(blank=True, default='', max_length=50)),
                ('rendimento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rendimento por unidade ou hectare', max_digits=12)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producao', to='diario_campo.registro')),
            ],
        ),
    ]
