# Generated by Django 6.0.2 on 2026-05-28 20:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_campo', '0012_alter_registro_tipo_atividade_custo_producao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producao',
            name='registro',
        ),
        migrations.AlterField(
            model_name='registro',
            name='tipo_atividade',
            field=models.CharField(blank=True, choices=[('preparo_solo', 'Preparo do Solo'), ('plantio', 'Plantio'), ('adubacao', 'Adubação'), ('irrigacao', 'Irrigação'), ('capina', 'Capina / Controle de Mato'), ('controle_pragas_doencas', 'Controle de Pragas e Doenças'), ('energia_combustivel', 'Energia / Combustível'), ('transporte_embalagem', 'Transporte / Embalagem'), ('colheita', 'Colheita')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='registro',
            name='valor_gasto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo total da atividade', max_digits=12),
        ),
        migrations.DeleteModel(
            name='Custo',
        ),
        migrations.DeleteModel(
            name='Producao',
        ),
    ]
